from collections.abc import Sequence

import pytest

from logicblocks.event.processing import (
    ProcessStatus,
    determine_multi_process_status,
)


def _ids(status: Sequence[ProcessStatus] | ProcessStatus) -> str:
    if isinstance(status, ProcessStatus):
        return status.value
    else:
        return "[" + "+".join(s.value for s in status) + "]"


@pytest.mark.parametrize(
    "statuses, expected_status",
    argvalues=[
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.INITIALISED,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.INITIALISED,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STARTING,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.WAITING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.RUNNING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.WAITING,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.RUNNING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.RUNNING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.RUNNING,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPING,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPED,
        ),
        (
            (
                ProcessStatus.STOPPED,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.ERRORED,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.UNKNOWN,
            ),
            ProcessStatus.UNKNOWN,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.INITIALISED,
            ),
            ProcessStatus.INITIALISED,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.STARTING,
            ),
            ProcessStatus.STARTING,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.WAITING,
            ),
            ProcessStatus.WAITING,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.RUNNING,
            ),
            ProcessStatus.RUNNING,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.STOPPING,
            ),
            ProcessStatus.STOPPING,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.STOPPED,
            ),
            ProcessStatus.STOPPED,
        ),
        (
            (
                ProcessStatus.UNKNOWN,
                ProcessStatus.ERRORED,
            ),
            ProcessStatus.ERRORED,
        ),
        ([], ProcessStatus.UNKNOWN),
    ],
    ids=_ids,
)
def test_determine_multi_process_status(statuses, expected_status):
    assert determine_multi_process_status(*statuses) == expected_status
