import pytest

from logicblocks.event.processing import (
    ProcessStatus,
    determine_multi_process_status,
)


@pytest.mark.parametrize(
    "status_1, status_2, expected_status",
    [
        (
            ProcessStatus.INITIALISED,
            ProcessStatus.INITIALISED,
            ProcessStatus.INITIALISED,
        ),
        (
            ProcessStatus.RUNNING,
            ProcessStatus.RUNNING,
            ProcessStatus.RUNNING,
        ),
        (
            ProcessStatus.STARTING,
            ProcessStatus.INITIALISED,
            ProcessStatus.STARTING,
        ),
        (
            ProcessStatus.STARTING,
            ProcessStatus.RUNNING,
            ProcessStatus.RUNNING,
        ),
        (
            ProcessStatus.STARTING,
            ProcessStatus.STOPPED,
            ProcessStatus.STOPPING,
        ),
        (
            ProcessStatus.STARTING,
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.RUNNING,
            ProcessStatus.INITIALISED,
            ProcessStatus.STARTING,
        ),
        (
            ProcessStatus.INITIALISED,
            ProcessStatus.RUNNING,
            ProcessStatus.STARTING,
        ),
        (
            ProcessStatus.ERRORED,
            ProcessStatus.RUNNING,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.RUNNING,
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.ERRORED,
            ProcessStatus.INITIALISED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.INITIALISED,
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.STOPPED,
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.ERRORED,
            ProcessStatus.STOPPED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
            ProcessStatus.ERRORED,
        ),
        (
            ProcessStatus.STOPPED,
            ProcessStatus.INITIALISED,
            ProcessStatus.STOPPING,
        ),
        (
            ProcessStatus.INITIALISED,
            ProcessStatus.STOPPED,
            ProcessStatus.STOPPING,
        ),
        (
            ProcessStatus.STOPPED,
            ProcessStatus.RUNNING,
            ProcessStatus.STOPPING,
        ),
        (
            ProcessStatus.RUNNING,
            ProcessStatus.STOPPED,
            ProcessStatus.STOPPING,
        ),
        (
            ProcessStatus.STOPPED,
            ProcessStatus.STOPPED,
            ProcessStatus.STOPPED,
        ),
    ],
)
def test_determine_multi_process_status(status_1, status_2, expected_status):
    assert (
        determine_multi_process_status(status_1, status_2) == expected_status
    )
